### ISSUE TITLE
Uploading field persists forever if uploads fails

### ISSUE THREAD

**Issue by hanzei** [streamer45/mattermost-plugin-screen#3]
If the video upload failed, `Uploading...` is shown forever. Only a hard reload makes is disappear. 

![Screenshot from 2020-04-23 11-35-51](https://user-images.githubusercontent.com/16541325/80084089-b47d1780-8556-11ea-8e43-e7ba7ccef425.png)

**Comment by streamer45** [comment]
Should be now fixed by https://github.com/streamer45/mattermost-plugin-screen/commit/fe54fedc39d0e9177056ddd829211dee90952e05.

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,
ich bin vom 8.6. bis zum 12.6. nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.
Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.
In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de)
Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145 | FAX +49 (0)571-502-66-145
j.rusch@schaeferbarthold.de
______________________________________________________________________
Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de
Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold
Should be now fixed by https://github.com/streamer45/mattermost-plugin-screen/commit/fe54fedc39d0e9177056ddd829211dee90952e05.

**Comment by hanzei** [comment]
Tested and works! Thanks for the fix :+1:

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,
ich bin vom 8.6. bis zum 12.6. nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.
Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.
In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de)
Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145 | FAX +49 (0)571-502-66-145
j.rusch@schaeferbarthold.de
______________________________________________________________________
Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de
Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold
Closed #3.

-- 
You are receiving this because you commented.
Reply to this email directly or view it on GitHub:
https://github.com/streamer45/mattermost-plugin-screen/issues/3#event-3429047413
